% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Feb-2016 11:29:01
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

ds = saveVarsMat.ds; % <1x1 basic_DS> unsupported class

clear saveVarsMat;
